### ISSUE TITLE
Community MuseScore plugin documentation

### ISSUE THREAD

**Issue by jgadsden** [eduardomourar/fingering-diagram#14]
Could we have an update in the MuseScore community documentation for this plugin to show support for Tin + Low whistle:
https://musescore.org/en/project/fingering-diagram 
I can then link across to it from the MuseScore group : https://musescore.com/groups/tin-whistle-music
Many thanks @eduardomourar

**Comment by eduardomourar** [comment]
@jgadsden , thank you for your help. I have updated the MuseScore community documentation. Just keep in mind that Fingering Diagram plugin only supports MuseScore v3.2.1 or higher, so people in older v3 versions should keep using your plugin.

**Comment by jgadsden** [comment]
Many thanks for this, I will put this advice on the Tin Whistle group.
