### ISSUE TITLE
Support for Alto Recorder fingering

### ISSUE THREAD

**Issue by eduardobaitello** [eduardomourar/fingering-diagram#17]
Currently, only the Soprano recorder is supported.

This is a feature request to support Alto Recorder fingering.

**Comment by eduardomourar** [comment]
It should not be hard considering that it is exactly the same fingering as soprano but a fifth down. We can make the distinction based on the musicXML ID of the staff:  `wind.flutes.recorder.alto`.

**Comment by eduardomourar** [comment]
@eduardobaitello, see if the PR #18 is what you expected and I'll make a release for it.

**Comment by eduardobaitello** [comment]
@eduardomourar I tested your `fingeringdiagram.qml` from PR #18 using the `Alto Recorder` instrument and it worked like a charm:

![alto_recorder_fingering](https://user-images.githubusercontent.com/25592626/85626518-8f368380-b643-11ea-9401-bd5b5a81b609.png)


I'm using Musescore 3.2.3 on Ubuntu 18.04.4.

**Comment by eduardomourar** [comment]
Available now in [v1.3.0](https://github.com/eduardomourar/fingering-diagram/releases/tag/v1.3.0).

**Comment by eduardobaitello** [comment]
Thanks for the feature @eduardomourar!
