### ISSUE TITLE
Plugin don't load on MS 3.6.2

### ISSUE THREAD

**Issue by nucklearproject** [eduardomourar/fingering-diagram#23]
Solution: 
Change  the method  FingeringClass Line 25 and 555  lowerCase to  fingeringClass

**Comment by eduardomourar** [comment]
I will have a look and create a release soon with the fix.

**Comment by eduardomourar** [comment]
Released [v1.6.0](https://github.com/eduardomourar/fingering-diagram/releases/tag/v1.6.0) with proposed fix.
