### ISSUE TITLE
Can't make it work in musescore 3.2.3 (debian bullseye)

### ISSUE THREAD

**Issue by YruamaLairba** [eduardomourar/fingering-diagram#35]
Hi,
I'm trying to use this plugin with musescore 3.2.3 provided by debian and it doesn't work:
The following seems ok:
- I installed the Fiati font and i can see it in my system font navigator.
- The plugin seems to load correctly, it appear in the plugin menu.

To check if this plugin work, i do the following action:
- create a new document with only a flute score
- add some random notes in the score
- select those notes and click on plugins>fingering diagram

Result: Nothing happen. I even run musescore in a terminal to show some error but i see nothing relevant, i just see this:
```
qml: Selected staves 0 - 0 - End position: 2400
qml: Staff 0 instrument: wind.flutes.flute
Signal QQmlEngine::quit() emitted, but no receivers connected to handle it.
```

**Comment by lgvr123** [comment]
MS3.2.3 is pretty old. If you want to stick to 3.x family I'll advise you to move to 3.6.2 (or even the unofficial 3.7).

**Comment by YruamaLairba** [comment]
Sorry, i forgot to update and close the issue. The problems seems to be on the debian side, i tryed the 3.2.3 appimage it  worked. However, the result is not what i was searching so i didn't search further. I don't know where to get the 3.6.2 version, the last 3.x version i can find on the website is 3.2.3.

**Comment by lgvr123** [comment]
Indeed. I can' find a 3.6.2 appImage :-/ 
Since the release of MuseScore4.0, one can no longer download a 3.6.2 appImage. 
Maybe should you ask on [the official forums](https://musescore.org/en/forum).
