### ISSUE TITLE
Support for Saxophone fingering

### ISSUE THREAD

**Issue by eduardomourar** [eduardomourar/fingering-diagram#5]
The initial ones have been added, but we need to add the full range.

**Comment by Khrisbie** [comment]
Hi, with my son who's playing the saxophone, we modified the plugin to add saxophone fingering. Here is the mapping :
`				this.mapping = [
					// 1st Octave (A3-B4)
					'\uE299\uE284\uE286\uE287\uE293\uE294\uE296\uE298',
                                        '\uE284\uE286\uE287\uE28E\uE293\uE294\uE296\uE298',
                                        '\uE284\uE286\uE287\uE28D\uE293\uE294\uE296\uE298',
                                        '\uE284\uE286\uE287\uE293\uE294\uE296\uE298',
                                        '\uE284\uE286\uE287\uE28C\uE293\uE294\uE296\uE298',
                                        '\uE284\uE286\uE287\uE293\uE294\uE296',
                                        '\uE284\uE286\uE287\uE293\uE294\uE296\uE297',
                                        '\uE284\uE286\uE287\uE293\uE294',
                                        '\uE284\uE286\uE287\uE293',
                                        '\uE284\uE286\uE287\uE294',
                                        '\uE284\uE286\uE287',
                                        '\uE284\uE286\uE287\uE28B',
                                        '\uE284\uE286',
                                        '\uE284\uE285',
                                        '\uE284',
					// 2nd Octave (C5-B5)
					'\uE286',
                                        '',
                                        '\uE282\uE284\uE286\uE287\uE293\uE294\uE296',
                                        '\uE282\uE284\uE286\uE287\uE293\uE294\uE296\uE297',
                                        '\uE282\uE284\uE286\uE287\uE293\uE294',
                                        '\uE282\uE284\uE286\uE287\uE293',
                                        '\uE282\uE284\uE286\uE287\uE294',
                                        '\uE282\uE284\uE286\uE287',
                                        '\uE282\uE284\uE286\uE287\uE28B',
                                        '\uE282\uE284\uE286',
                                        '\uE282\uE284\uE285',
                                        '\uE282\uE284',
					// 3nd Octave (C6-B6)
					'\uE282\uE286',
                                        '\uE282',
                                        '\uE282\uE289',
                                        '\uE282\uE288\uE289',
                                        '\uE282\uE288\uE289\uE28F',
                                        '\uE282\uE288\uE289\uE28A\uE28F',
                                        '','','','','','',
					// 4th Octave (C7-D8)
					'','','','','','','','','','','','',
				];
`
By the way, it would be great to have the possibility, as an option, to display alternate fingering.
Good job for this plugin !

**Comment by eduardomourar** [comment]
@Khrisbie , thank you very much for this! I will take a look and make a release as soon as possible.

**Comment by eduardomourar** [comment]
Available now in [v1.2.0](https://github.com/eduardomourar/fingering-diagram/releases/tag/v1.2.0).
