### ISSUE TITLE
Support for Tin Whistle and Low Whistle fingering

### ISSUE THREAD

**Issue by jgadsden** [eduardomourar/fingering-diagram#9]
It would be good to add a new tab for the Tin Whistle and Low Whistle. These whistles come in various sizes that are tuned to various keys:
- "D Low Whistle" tuned to D4
- "F Low Whistle" tuned to F4
- "G Low Whistle" tuned to G4
- "B♭ Tin Whistle" tuned to key B♭
- "C Tin Whistle" tuned to C5
- "D Tin Whistle" tuned to D5
- "E♭ Tin Whistle" tuned to E♭
- "F Tin Whistle" tuned to F5
- "G Tin Whistle" tuned to G5
this is a companion issue to https://github.com/jgadsden/tin-whistle-tablature/issues/28
This needs the fiati font to be extended for Whistles, and an issue is raised for this : 
https://github.com/eduardomourar/fiati/issues/5

Here are the steps we will take to achieve this:
- [x] Add these charts to the Fiati font (https://github.com/eduardomourar/fiati/issues/5)
- [x] Update [spreadsheet](https://github.com/eduardomourar/fingering-diagram/blob/feature/add-whistles/fingering.ods) to list basic instrument fingering
- [x] Add Whistles note mapping to the [plugin itself](https://github.com/eduardomourar/fingering-diagram/blob/feature/add-whistles/fingeringdiagram.qml)
- [x] Test plugin and add new instrument (Tin Whistle in D) to [sample MuseScore file](https://github.com/eduardomourar/fingering-diagram/blob/feature/add-whistles/sample.mscx)

**Comment by eduardomourar** [comment]
Here are the steps we will taking to achieve this:

- [ ] Add these charts to the Fiati font (https://github.com/eduardomourar/fiati/issues/5)
- [ ] Update spreadsheet to list basic instrument fingering
- [ ] Add Whistles note mapping to the plugin itself
- [ ] Test plugin and add new instrument (probably only C Tin Whistle) to sample MuseScore file

**Comment by jgadsden** [comment]
Yes, looks a good plan @eduardomourar . A suggestion may be to add the D Tin Whistle to the sample MuseScore file rather than one tuned to C, as D tuning is much more common than C tuning for Tin Whistles. In the music shops typically about 80% to 90% are D whistles, the rest being a mixed bag of C, Bflat, Eflat and maybe F and G.

**Comment by jgadsden** [comment]
Hello @eduardomourar - nearly finished the Tin Whistle tab for the spreadsheet. The half notes have me confused though, could you supply the unicode for the halfnotes : 
- LH 1st finger
- LH 2nd finger
- LH 3rd finger
- RH 2nd finger
- RH 3rd finger

Many thanks, I can then put a pull request to your branch feature/add-whistles

**Comment by eduardomourar** [comment]
You can find the list of unicode characters and its description here: https://github.com/eduardomourar/fiati/blob/master/source/glyph_data.csv

Respectively, `\uE3DF`, `\uE3E1`, `\uE3E2`, `\uE3E5`, `\uE3E6`. Also, you can check the unicode for the '+' at the bottom `woodwindOverblownOctave1` and '++' is `woodwindOverblownOctave2`.

**Comment by eduardomourar** [comment]
@jgadsden, I finished #12. Let me know what you think and then we can merge it.

**Comment by jgadsden** [comment]
Hello @eduardomourar - generally looking excellent, thankyou, but with one bug that is easily fixed.  This is an edge case, but when more than one whistle staff is included in the score then the D Tin Whistle Staff will use whatever 'transpose' is currently set - which is '0' initially, but if a staff for a tin whistle has already been processed with a 'transpose' value different to 0 (say 2 for a C Tin Whistle) then the D Tin Whistle staff fingering will use this 'transpose' value instead of the correct value of '0'.

To test this, construct MuseScore score with 3 staves in order 'D Tin Whistle', 'C Tin Whistle' and 'D Tin Whistle'. Apply fingeringdiagram.qml plugin and observe first two staves are correct, but 3rd staff has C tuning not the expected D tuning.
Alternatively this can be observed when using plugin for the score https://github.com/jgadsden/tin-whistle-tablature/tree/master/examples/tin_whistle_test.mscz

**Comment by jgadsden** [comment]
Good results from #12 - many thanks. This looks better than https://github.com/jgadsden/tin-whistle-tablature - will add to the MuseScore discussion groups.
